### PR TITLE
Cleanups around the KNXBridgeBaseThingHandler

### PR DESCRIPTION
**Pull request by sjsf**
Several cleanups around the KNXBridgeBaseThingHandler

* factored out quite a lot of common/unrelated stuff
* dropped useless if/else statements where both blocks are identical
* fixed state handling
* removed unused dependencies
* made dependency to rxtx library optional (as you really don't need it when not using a serial bridge)
* removed dependency to DSL bundles
* removed dependency to openHAB (!)
* turned bundle imports into package imports 
* update to Java 8
* update calimero to latest stable (!) version (2.3)
* factored out the ThingProvider
* fixed service registration handling in the factory
* fixed service dependency injection
* tried to avoid duplicate code wherever possible
* fixed OSGi 4.2 compatibility
* added support for NAT
* fixed log statements, adapted severity
* and a lot of minor stuff like empty empty lines, comments, etc.

### CODE REVIEW

**Comment by sjsf** [comment]
@kgoderis not sure if you can use it now or not. If you want to cleanup yourself first, that's fine by me, of course! Totally up to you.

**Comment by kgoderis** [comment]
@sjka Tx Simon. Massive changes here, and I think most for the better 👍 . FYI for reviewing purposes I in fact try to keep most of the OH1 code "as is" to make things easier for @kaikreuzer. 
Did you already test all the changes you provide? 

Give me some time to review and merge, and then let's do round #2 from there

**Comment by sjsf** [comment]
No worries, as I said, there is no hurry from my side. I tried to keep the commits as small as possible, so it will be easy to rebase/cherry-pick them later on. It's btw much easier to look at them one by one. I have to admit that the overall diff looks pretty messy... 

My hope was that it's easier for you than leaving comments everywhere and making you do the same. As I said, I'm also happy if you do your planned cleanups first and then I will go trough the commits here and see what's left. I have to admit that I didn't care much about keeping the code close to the OH1 version, so I certainly broke with this paradigm.

I tried testing the changes as good as I can with my setup. But e.g. the NAT support was needed as I'm running OH in a docker container via TUNNEL type, that's tested. But I have no serial adapter etc. and my setup for sure is smaller than yours, so it will for sure be necessary to run it through your setup. 

So, as I said: Take your time, no hurry at all!

**Review by kgoderis — COMMENTED** [review]
.

**Comment by kaikreuzer** [comment]
>  try to keep most of the OH1 code "as is" to make things easier for @kaikreuzer

No need to - this code is the first ever written for openHAB 7 years ago, so it might be time to do some refactoring for the better :-)

**Pull request closed without merging**
