### PR TITLE
KNX split

### PR DESCRIPTION
**Pull request by sjsf**
As discussed in https://github.com/openhab/openhab2-addons/pull/2294#issuecomment-303666389, this is my attempt to split the knx binding up into a "core" and "generic" extension part. 

Since you [suggested yourself](https://github.com/openhab/openhab2-addons/pull/2294#issuecomment-303950776) to create a tool to convert knx project files into DSL files, I didn't put much love into the generic extension (yet). I just made sure it still compiles and IMHO it should still work (can't _really_ test the discovery as it seems it does not work in TUNNEL mode...?).

In the "usual" manner, I tried to also cleanup the code a little by factoring out common stuff. I kept these in small commits again, so I can easily ommit/fix something if you don't like it.

Some things to notice:

* There are now "basic" thing types with a "KNXBasicThingHandler" in the core binding, which only supports the "feature" oriented channel types (i.e. not the "generic" one). Of course, I simply kept those that you defined for now.
* Regarding the "circular update problem", I solved it in the "basic" handler in the following way:
  * The "READ" GAs (as reported by the channel configuration, not the KNX bus of course) only update the channels's states, but nothing is done for them in `handleCommand()`
  * The "WRITE" GAs (as reported by the channel configuration, not the KNX bus of course) will be used in `handleCommand()` only.
  * The `handleUpdate()` method pretty much does nothing for these types, as it is assumed that the main source is within the KNX bus.
* As an example case for a scenario where the main source is openHAB (i.e. another device external to the KNX bus maintains the _real_ state), I added a "wallbutton" channel type.
  * It works inverse to the statusswitch type: it "WRITES" to the statusGA but "READS" the switchGA
  * For these kind of devices I coined the term "slave". Like it or change it, I don't mind.
  * Consequently, for such "slave" devices, the `KNXBasicThingHandler` writes to the bus in `handleUpdate()`, but does nothing in `handleCommand`
  * If anything is received on the "READ" GAs, it will post a corresponding command to the channel
  * Therefore, this is how it works when having an item liked to the `knx:wallbutton` and `otherbinding:lamp`:
    * I switch on the lamp within openHAB (e.g. basic UI): 
      1. knx and the otherbinding recieve the command
        * knx binding ignores it
        * otherbinding uses it to send a new value to its lamp
      2. otherbinding gets the new value from the device and updates the channel's state
      3. the value of the linked item gets updated by the framework
      4. the knx binding gets a `handleUpdate()` call with the new value
      5. the knx binding writes the new value to the knx bus
      6. the wallbutton lights up
    * I tap the knx wall button 
      1. knx binding receives the message on the switchGA
      2. it posts a Command to the channel on the event bus
      3. the ThingManager forwards this command to otherbinding
      4. otherbinding uses it to send a new value to its lamp
      5. otherbinding gets the new value from the device and updates the channel's state
      6. knx binding writes to the statusGA the new value
    * Switch on the lamp via another app which communicates with the lamp directly
      1. I switch on the lamp, openHAB and KNX is completely unaware of this yet
      2. otherbinding gets the new value from the device and updates the channel's state
      3. the value of the linked item gets updated by the framework
      4. the knx binding gets a `handleUpdate()` call with the new value
      5. the knx binding writes the new value to the knx bus
      6. the wallbutton lights up
* Having the "auto-update" feature enabled (as it is now) massively improves the reaction speed of all "UIs" (including the KNX wall button, of course. It also doesn't produce cycles, but can lead to duplicate messages to the bus (first the "auto" update, second the "real" update coming from the other binding). But that's expected and is actually the case with every binding. So it does not hurt to leave it enabled (and helps in cases where the actor does not respond with a status GA).
* Same applies for "non-slave" types, of course. But as the bus is quick, it is less noticeable.
* As so far it looks like the "slave" use-cases are the complete inverse of the ordinary ones, maybe it rather makes sense to give the existing channel-types a boolean "slave" configuration option, which simply inverses READ & WRITE GAs. But I haven't thought this through completely. Maybe only for more "generic" ones like "string", "number", "boolean" - if we want to keep them at all. They actually break with the [usual paradigm of fine-grained channel-types](https://www.eclipse.org/smarthome/documentation/development/bindings/thing-definition.html#channels) which we have in bindings. Actually the guidance would be to create many more channel types than what we currently have.
* For the discovery service which now sits in the "generic" extension, I created a hook in the "basic" thing handler factory, so it is possible to register a "KNXBridgeHandlerTracker" in order to (de)register a discovery service for each of them
* The KNX project importer is currently not automatically registered, i.e. is dead right now. As its approach was not the promising one, I assume this is okay, but wanted to make this transparent here.

I hope that's it for now 😄  Have look, and once it is merged we can start the "real" review of the basic part and clarify the remaining questions. I'd even suggest to split "basic" and "generic" parts into separate PRs then, so we can stay focused.

### CODE REVIEW

**Comment by sjsf** [comment]
I took the freedom to create https://github.com/openhab/openhab2-addons/pull/2323, containing only the basic part, which is not meant to be disrespectful and hopefully is okay for you...?

At the moment is identical to what's in here, so you should be able to easily continue with the generic part. You'd simply need to throw away the basic part here, later on.

**Comment by kgoderis** [comment]
> As discussed in openhab#2294 (comment), this is my attempt to split the knx binding up into a "core" and "generic" extension part.

@sjka I will try to go over all this over the weekend. I had some other things in mind to implement and will try to add these (like https://github.com/openhab/openhab2-addons/pull/2294#issuecomment-303950776). I also had "aha" moment yesterday in the sense that all the "auto-briding" stuff can be covered if we allow no bridging of Command and States for Channels that belong to the same Thing, and if we allow to create more than one thing using the same Individual Address in its configuration. So for example, a multi-channel actor can be split up in 4 or 8 things, each representing a roller shutter or whatever. In each Thing there will be some Channels ("generic" ones, or specfic ones like "rollershutter" channel, but assume it is all generic ones), then any Command send on one Channel and data coming back over the bus, will be discarded by the other Channels of that Thing.

The only thing I am not sure about is how I can contribute here, practically? I continue to work on kgoderis:knx-rebase, with the commits here above? Or shall I clone your repo so that I can contribute commits to be included in  openhab#2323 ?

**Comment by lewie** [comment]
@sjka, @kgoderis, wow, I'm looking forward to the first tests.

 1. Where will you place the part of the external requests from the KNX bus to openHAB (KNX IO with groupReadRequest / groupReadResponse)?
     - Should this function be provided in the "KNX basic" bundle or in the "KNX generic" extension?
     - Or does it even need a third extension?

 2. Please do not forget KNX Mode ROUTING, since the KNX-bus unexpectedly behaves differently there.

I have a KNX test station, if I should test something special plese tell me, so I can support you.

**Comment by lewie** [comment]
@kgoderis, very sad.... :-(

**Pull request closed without merging**
